apiVersion: v1
kind: Service
metadata:
  name: reactsvc
  labels:
    name: reactsvc
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
      targetPort: 3000  
  selector:
    tier: react
    

---

apiVersion: v1
kind: Service
metadata:
  name: djangosvc
  labels:
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    tier: django


---

apiVersion: v1
kind: Service
metadata:
  name: postgressvc
  labels:
    tier: postgres
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    tier: django
    
